services:
  db:
    image: postgres:18.1-alpine3.23
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  redis:
    depends_on:
      - db
    image: redis:8.6-rc1-alpine3.23
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 100mb
    restart: unless-stopped

  blocklist:
    container_name: blocklist
    depends_on:
      - db
      - redis
    volumes:
      - ./core:/app/core
    build:
      context: ./blocker_service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"

  auth_service:
    container_name: auth_service
    depends_on:
      - blocklist
    volumes:
      - ./core:/app/core
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"

  backend:
    container_name: backend
    depends_on:
      - auth_service
      - blocklist
    volumes:
      - ./core:/app/core
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  redis_data:
